Bump @alpinejs/persist from 3.13.7 to 3.14.1 (#7084)
Bumps
[@alpinejs/persist](https://github.com/alpinejs/alpine/tree/HEAD/packages/persist)
from 3.13.7 to 3.14.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/alpinejs/alpine/releases"><code>@​alpinejs/persist</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v3.14.1</h2>
<h2>Changed</h2>
<ul>
<li>Minor grammar correction in the for directive docs <a
href="https://redirect.github.com/alpinejs/alpine/pull/4266">#4266</a></li>
<li>:bug: Fixes issue with setters accessing deeply nested data <a
href="https://redirect.github.com/alpinejs/alpine/pull/4265">#4265</a></li>
<li>[UI][Tabs] Prevent tab focus on mousedown <a
href="https://redirect.github.com/alpinejs/alpine/pull/4239">#4239</a></li>
<li>[CSP] Add support for nested properties to CSP build <a
href="https://redirect.github.com/alpinejs/alpine/pull/4238">#4238</a></li>
</ul>
<h2>v3.14.0</h2>
<h2>Changed</h2>
<ul>
<li>:sparkles: Enhances clicks with key modifiers <a
href="https://redirect.github.com/alpinejs/alpine/pull/4209">#4209</a></li>
<li>Update transition.md - changed span to div <a
href="https://redirect.github.com/alpinejs/alpine/pull/4215">#4215</a></li>
<li>collapse: remove overflow hidden even if height does not match
perfect <a
href="https://redirect.github.com/alpinejs/alpine/pull/4203">#4203</a></li>
<li>Fix error: TypeError: i is not a function <a
href="https://redirect.github.com/alpinejs/alpine/pull/4204">#4204</a></li>
<li>Adjust code block according to example <a
href="https://redirect.github.com/alpinejs/alpine/pull/4197">#4197</a></li>
<li>Higher visibility in docs about needing x-data for things to work <a
href="https://redirect.github.com/alpinejs/alpine/pull/4194">#4194</a></li>
</ul>
<h2>v3.13.10</h2>
<h2>Changed</h2>
<ul>
<li>Comma modifier to keyup and keydown events <a
href="https://redirect.github.com/alpinejs/alpine/pull/4170">#4170</a></li>
<li>Fix morphing root level state <a
href="https://redirect.github.com/alpinejs/alpine/pull/4169">#4169</a></li>
<li>Fix morph when x-for is used inside x-teleport <a
href="https://redirect.github.com/alpinejs/alpine/pull/4168">#4168</a></li>
<li>Fix form reset for x-model radio, checkbox arrays, select multiple
and various modifiers <a
href="https://redirect.github.com/alpinejs/alpine/pull/4159">#4159</a></li>
<li>Wrong plugin name in Sort docs <a
href="https://redirect.github.com/alpinejs/alpine/pull/4165">#4165</a></li>
</ul>
<h2>v3.13.9</h2>
<h2>Changed</h2>
<ul>
<li>Add &quot;sort&quot; plugin <a
href="https://redirect.github.com/alpinejs/alpine/pull/4137">#4137</a></li>
<li>Add missing plugin warnings <a
href="https://redirect.github.com/alpinejs/alpine/pull/4158">#4158</a></li>
<li>Change to <code>x-sort:item</code>, add sorting class to body, and
use <code>x-sort:group</code> <a
href="https://redirect.github.com/alpinejs/alpine/pull/4161">#4161</a></li>
<li>Remove extra destroyTree call <a
href="https://redirect.github.com/alpinejs/alpine/pull/4151">#4151</a></li>
<li>Fix x-on with both self and once <a
href="https://redirect.github.com/alpinejs/alpine/pull/4152">#4152</a></li>
<li>Documentation issue: Event name in code snippet and description
doesn't match in dispatch.md <a
href="https://redirect.github.com/alpinejs/alpine/pull/4141">#4141</a></li>
<li>Fix some typos <a
href="https://redirect.github.com/alpinejs/alpine/pull/4134">#4134</a></li>
<li>Chore: remove repetitive words <a
href="https://redirect.github.com/alpinejs/alpine/pull/4132">#4132</a></li>
</ul>
<h2>v3.13.8</h2>
<h2>Changed</h2>
<ul>
<li>Cleanup after <code>x-bind:class</code> and other attribute
modifications <a
href="https://redirect.github.com/alpinejs/alpine/pull/4111">#4111</a></li>
<li>Bug: Fixes x-model.fill when used with debounce <a
href="https://redirect.github.com/alpinejs/alpine/pull/4103">#4103</a></li>
<li>Remove hidden from booleanAttributes <a
href="https://redirect.github.com/alpinejs/alpine/pull/4099">#4099</a></li>
<li>Fix fill modifier for radio buttons <a
href="https://redirect.github.com/alpinejs/alpine/pull/4101">#4101</a></li>
<li>Add missing border to fill example <a
href="https://redirect.github.com/alpinejs/alpine/pull/4104">#4104</a></li>
<li>Fixed persist crash when the stored value is undefined <a
href="https://redirect.github.com/alpinejs/alpine/pull/4091">#4091</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/alpinejs/alpine/commit/b4fa14e49d8175fc29b6e8a46f4e016d741b75a4"><code>b4fa14e</code></a>
wip</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/ac7c251e8fa99c0fd6d1bb9373d1d7f75449b5c9"><code>ac7c251</code></a>
bump version</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/851dc0ed2e15f34a7de6546ad71b581610adec58"><code>851dc0e</code></a>
bump version</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/6ac7cf209664aab72e82b1a24feb91f691400fd0"><code>6ac7cf2</code></a>
wip</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/85ff820f4595e7332553ebbada505506338506aa"><code>85ff820</code></a>
bump to 3.13.8</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/c38a45f3b6393e4b09cb8d7d4a04180d92b51ac3"><code>c38a45f</code></a>
Fixed persist crash when the stored value is undefined (<a
href="https://github.com/alpinejs/alpine/tree/HEAD/packages/persist/issues/4091">#4091</a>)</li>
<li>See full diff in <a
href="https://github.com/alpinejs/alpine/commits/v3.14.1/packages/persist">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@alpinejs/persist&package-manager=npm_and_yarn&previous-version=3.13.7&new-version=3.14.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>