Bump alpinejs from 3.13.10 to 3.14.1 (#7081)
Bumps
[alpinejs](https://github.com/alpinejs/alpine/tree/HEAD/packages/alpinejs)
from 3.13.10 to 3.14.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/alpinejs/alpine/releases">alpinejs's
releases</a>.</em></p>
<blockquote>
<h2>v3.14.1</h2>
<h2>Changed</h2>
<ul>
<li>Minor grammar correction in the for directive docs <a
href="https://redirect.github.com/alpinejs/alpine/pull/4266">#4266</a></li>
<li>:bug: Fixes issue with setters accessing deeply nested data <a
href="https://redirect.github.com/alpinejs/alpine/pull/4265">#4265</a></li>
<li>[UI][Tabs] Prevent tab focus on mousedown <a
href="https://redirect.github.com/alpinejs/alpine/pull/4239">#4239</a></li>
<li>[CSP] Add support for nested properties to CSP build <a
href="https://redirect.github.com/alpinejs/alpine/pull/4238">#4238</a></li>
</ul>
<h2>v3.14.0</h2>
<h2>Changed</h2>
<ul>
<li>:sparkles: Enhances clicks with key modifiers <a
href="https://redirect.github.com/alpinejs/alpine/pull/4209">#4209</a></li>
<li>Update transition.md - changed span to div <a
href="https://redirect.github.com/alpinejs/alpine/pull/4215">#4215</a></li>
<li>collapse: remove overflow hidden even if height does not match
perfect <a
href="https://redirect.github.com/alpinejs/alpine/pull/4203">#4203</a></li>
<li>Fix error: TypeError: i is not a function <a
href="https://redirect.github.com/alpinejs/alpine/pull/4204">#4204</a></li>
<li>Adjust code block according to example <a
href="https://redirect.github.com/alpinejs/alpine/pull/4197">#4197</a></li>
<li>Higher visibility in docs about needing x-data for things to work <a
href="https://redirect.github.com/alpinejs/alpine/pull/4194">#4194</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/alpinejs/alpine/commit/b4fa14e49d8175fc29b6e8a46f4e016d741b75a4"><code>b4fa14e</code></a>
wip</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/541cb8ef8fb169cdb6032fdf920169ffd083c812"><code>541cb8e</code></a>
:bug: Fixes issue with setters accessing deeply nested data (<a
href="https://github.com/alpinejs/alpine/tree/HEAD/packages/alpinejs/issues/4265">#4265</a>)</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/ac7c251e8fa99c0fd6d1bb9373d1d7f75449b5c9"><code>ac7c251</code></a>
bump version</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/4fa8eafa0690a904c13f480d16e6d38576d64495"><code>4fa8eaf</code></a>
:sparkles: Enhances clicks with key modifiers (<a
href="https://github.com/alpinejs/alpine/tree/HEAD/packages/alpinejs/issues/4209">#4209</a>)</li>
<li><a
href="https://github.com/alpinejs/alpine/commit/ad13dbff725e5e13ecf36ebe9b8b45034ee58591"><code>ad13dbf</code></a>
Fix error: TypeError: i is not a function (<a
href="https://github.com/alpinejs/alpine/tree/HEAD/packages/alpinejs/issues/4204">#4204</a>)</li>
<li>See full diff in <a
href="https://github.com/alpinejs/alpine/commits/v3.14.1/packages/alpinejs">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=alpinejs&package-manager=npm_and_yarn&previous-version=3.13.10&new-version=3.14.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>